mforms: InputfieldDecorator::display
$cache
$displaycount
$displaycountidx
display
getDisabled
getRequired
getTemplateExtension
getType
getValue
setDisabled
setRequired
setValue
InputfieldDecorator::display ()
Definition at line 40 of file InputfieldDecorator.php.
References Decorator::$class, $content, Decorator::getClass(), Decorator::getSurroundedBy(), and getTemplateExtension().
{
    if($this->getSurroundedBy() === null) {
      self::$displaycountidx++;
      self::$displaycount[self::$displaycountidx] = 0;
    }
    $template_loader = $this->object->getTemplateLoader();
    $ext = $template_loader->getTemplateExtension();
    $template_loader->setTemplateExtension($this->getTemplateExtension());
    $class = $this->getClass();
    if(($file = $this->getFirstTemplateFile($class)) === null) {
      throw new BadMethodCallException("no template found for " . $class);
    }
    $template_loader->setTemplateExtension($ext);
    require $file;
    if(!isset($content)) {
      $content = "";
    }
    $this->cache[($this->getTemplateExtension() === '') ? 'main' : ltrim($this->getTemplateExtension(), ".")] = $content;
    self::$displaycount[self::$displaycountidx]++;
    if($this->object instanceof InputfieldDecorator) {
      $this->cache = array_merge($this->cache, $this->object->display());
    } else {
      $this->cache = array_merge($this->cache, array('main' => $this->object->display()));
      self::$displaycountidx--;
    }
    //var_dump($this->cache);
    self::$displaycount[self::$displaycountidx + 1]--;
    if(self::$displaycount[self::$displaycountidx + 1] === 0) {
      $num = 15;
      $n = 0;
      while($num != 0) {
        $num = 0;
        foreach($this->cache as $key => &$element) {
          foreach($this->cache as $key2 => $element2) {
            //echo 'str_replace(\'{"\' . ' . $key2 . ' . \'"}\', \'' . $element2 . '\', \'' . $element . '\')' . "\n";
            $element = str_replace('{"' . $key2 . '"}', $element2, $element, $n);
            //echo "RES: '" . $element . "'\n";
            $num += $n;
          }
        }
      }
      $first = true;
      foreach($this->cache as $key => &$value) {
        $value = preg_replace('/\{"[^\{]*"\}/i', "", $value);
        if($first) {
          $max = strlen($value);
          $max_idx = $key;
          $first = false;
        } else {
          if(strlen($value) > $max) {
            $max = strlen($value);
            $max_idx = $key;
          }
        }
      }
      //echo "INDEX: '$max_idx'\n";
      //var_dump($this->cache);
      return $this->cache[$max_idx];
    } else {
      //var_dump($this->cache);
      return $this->cache;
    }
  }